name: goal_getters
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.4.0
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  image_path: "assets/Icon.png"
  android: true
  ios: true


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
